-- begin SAMPLE_DISCOUNT
create unique index IDX_SAMPLE_DISCOUNT_UNQ on SAMPLE_DISCOUNT (CUSTOMER_GRADE, PRODUCT_TYPE, DISCOUNT) ^
-- end SAMPLE_DISCOUNT
-- begin SAMPLE_CUSTOMER
create unique index IDX_SAMPLE_CUSTOMER_UNQ_EMAIL on SAMPLE_CUSTOMER (EMAIL) ^
-- end SAMPLE_CUSTOMER
-- begin SAMPLE_ORDER
alter table SAMPLE_ORDER add constraint FK_SAMPLE_ORDER_CUSTOMER foreign key (CUSTOMER_ID) references SAMPLE_CUSTOMER(ID)^
create index IDX_SAMPLE_ORDER_CUSTOMER on SAMPLE_ORDER (CUSTOMER_ID)^
-- end SAMPLE_ORDER
